### ISSUE TITLE
Is this still viable?

### ISSUE THREAD

**Issue by rylanharper** [estrattonbailey/klaviyo-subscribe#8]
Hey there @estrattonbailey! 👋

Really appreciate this little plugin. I used it a few years back it for a couple of projects, but I am just checking if this is still viable? I am potentially looking to integrate this with a Vue3 project for a client project I have going. 

Thanks!

**Comment by estrattonbailey** [comment]
Hey! Glad you've found it useful. I'm not 100% on the status of these APIs — been ages since I used Klaviyo — but I'm fairly certain that it's been used recently by some friends, so I'd say it's worth a shot.

**Comment by rylanharper** [comment]
Sounds good! I will go ahead and try it out. It seems the most recent reference to client-side endpoint `https://manage.kmail-lists.com/ajax/subscriptions/subscribe` is [this thread](https://community.klaviyo.com/lists-segments-and-profiles-35/using-the-api-to-subscribe-a-contact-to-a-list-4530) on the klaviyo forums about 5 months ago (not sure why I can't easily find this on the official documentation). So it seems everything is still the same as it was haha.

Thanks for the quick reply!

**Comment by estrattonbailey** [comment]
Nice, thanks for the update!
